[package]
name = "threadpool"
version = "0.1.0"
authors = ["Volodymyr Yevtushenko <volodymyr.yevtushenko@refinitiv.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
